# coding: utf-8

"""
    Content Moderation API

    API for content moderation and publishing platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_update import PostUpdate

class TestPostUpdate(unittest.TestCase):
    """PostUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostUpdate:
        """Test PostUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostUpdate`
        """
        model = PostUpdate()
        if include_optional:
            return PostUpdate(
                title = '',
                content = ''
            )
        else:
            return PostUpdate(
        )
        """

    def testPostUpdate(self):
        """Test PostUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
