# coding: utf-8

"""
    Content Moderation API

    API for content moderation and publishing platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.posts_api import PostsApi


class TestPostsApi(unittest.TestCase):
    """PostsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PostsApi()

    def tearDown(self) -> None:
        pass

    def test_create_post_posts_post(self) -> None:
        """Test case for create_post_posts_post

        Create Post
        """
        pass

    def test_get_post_posts_post_id_get(self) -> None:
        """Test case for get_post_posts_post_id_get

        Get Post
        """
        pass

    def test_list_posts_posts_get(self) -> None:
        """Test case for list_posts_posts_get

        List Posts
        """
        pass

    def test_publish_post_posts_post_id_publish_patch(self) -> None:
        """Test case for publish_post_posts_post_id_publish_patch

        Publish Post
        """
        pass

    def test_submit_post_posts_post_id_submit_post(self) -> None:
        """Test case for submit_post_posts_post_id_submit_post

        Submit Post
        """
        pass

    def test_update_post_posts_post_id_patch(self) -> None:
        """Test case for update_post_posts_post_id_patch

        Update Post
        """
        pass


if __name__ == '__main__':
    unittest.main()
